- hosts: localhost
  connection: local 
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: Build Maven
      command: mvn -f /var/lib/jenkins/workspace/Project-1/pom.xml clean package
