- hosts: localhost
  connection: local 
  become: true
  become_user: root
  gather_facts: false
  tasks:
    - name: Download Apache Maven
      get_url: url=https://mirrors.estointernet.in/apache/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.tar.gz dest=/tmp/apache-maven-3.8.5-bin.tar.gz
    - name: Untar Maven
      shell: chdir=/tmp creates=/opt/apache-maven- tar -zxf apache-maven-3.8.5-bin.tar.gz -C /opt
    - name: Build Maven
      shell: "mvn clean install"
